services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/database
      - DB_USERNAME=db_user
      - DB_PASSWORD=6xKo80d4r&p
      - ADMIN_API_KEY=&P6rjMqFe4P0j3XDH6#I2r
    depends_on:
      - db

  db:
    image: 'postgres:16'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=6xKo80d4r&p